/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode23

import java.io.File

class App {

    fun getDigits(s: String): Int {
        var tens = 0
        var ones = 0
        val listDigit =  mutableListOf("one", "two", "three", "four", "five", "six", "seven", "eight", "nine")
        val listSIndex = (listDigit.map { it.length - 1}).toMutableList()
        val listPIndex = mutableListOf(0,0,0,0,0,0,0,0,0)
        for( i in s.indices){
            if (s[i].isDigit() && tens==0){
            tens = s[i].digitToInt() * 10
            }else if(tens==0){
                for(j in listDigit.indices){
                    if (s[i] == (listDigit[j][listPIndex[j]])){
                        listPIndex[j] = listPIndex[j] + 1
                        if(listPIndex[j]==listDigit[j].length) {
                            tens = (j + 1) * 10
                            break
                        }

                    }
                }
            }
            val reverseIndex = s.length - i - 1
            if (s[reverseIndex].isDigit() && ones==0){
                ones = s[reverseIndex].digitToInt()
            }else if(ones==0){
                for(j in listDigit.indices){
                    if (s[reverseIndex] == (listDigit[j][listSIndex[j]])){
                       // println("s " + listDigit[j])
                        listSIndex[j] = listSIndex[j] - 1
                        if(listSIndex[j]==-1){
                            ones =  j + 1
                            break
                        }

                    }
                }
            }
        }
       // println(tens + ones)
        return tens + ones
    }
}

fun main() {
   val input: List<String> = object {}.javaClass.getResource("/day1").readText().split("\n")
    input.fold(0) { acc, s ->
        acc + App().getDigits(s)
    }.let(::println)

}
